version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: php-dev
    container_name: dp_content_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: dp_content_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8087:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db_content:
    image: mysql:5.7.22
    container_name: dp_content_db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: content
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: megaPass!
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_content_data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  cache:
    image: redis:5.0.9-alpine
    container_name: dp_content_cache
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  db_content_data:
    driver: local
